### ISSUE TITLE
Add automatic heroku build

### ISSUE THREAD

**Issue by rvillanueva** [codeforboston/bypath#23]
To deploy automatic build from Github to Heroku, I can either

1) Hook it up to my fork, but that requires me to pull changes to update from the main repo
2) Transfer Heroku ownership to one of you and you can link it to the codeforboston repo (probably makes the most sense)
3) Add me onto the codeforboston and I'll link it to Heroku

Deploy is available at https://snowranger.herokuapp.com

**Comment by irstacks** [comment]
The herokuapp site looks great. 

Number 2) sounds like a winner. We've got a team email account at snowranger.boston@gmail.com.

**Comment by rvillanueva** [comment]
Oops, apparently I lied--I can't do transfers laterally to other users. But it should be fairly easy to deploy for you. All you have to do is set up a Heroku account, create an app, and then automatically deploy from your Github repo (which is already set up).

Let me know when that works, and I can remove the snowranger.herokuapp.com domain from my account and you can use it for yours.

Cheers,
Ryan
