### ISSUE TITLE
No Linter

### ISSUE THREAD

**Issue by brandly** [codeforboston/bypath#70]
[In the wiki](https://github.com/codeforboston/bypath/wiki/Development-Practices#style-and-conventions), it mentions following AirBnB's style guide. However, this isn't enforced.

Would it be helpful to add eslint to enforce these rules?

**Comment by AlexMerritt** [comment]
Currently we are using these AirBnB's style guide as a guide. Currently we don't need to enforce these rules.

**Comment by brandly** [comment]
I always like having a linter to catch unused variables and unhandled errors for me, but not everyone cares for them. Thanks!
